Emit an error for traces without a master trace
This fixes a crash with debian.co.il, which was redirecting to another site.

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/mirror-team.debian.org/status/./generate", line 52, in job_consumer_proc
    i.prepare(dbh)
  File "/srv/mirror-team.debian.org/status/dmt/HierarchyGenerator.py", line 271, in prepare
    row['traces'].remove('master')
ValueError: list.remove(x): x not in list

Signed-off-by: Julien Cristau <jcristau@debian.org>